# Generated by Django 2.2.1 on 2019-05-09 17:43

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Modulo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default=None, max_length=50)),
                ('numero', models.IntegerField(default=None)),
                ('descripcion', models.CharField(default=None, max_length=250)),
                ('topic', models.CharField(default=None, max_length=50)),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='dht',
            fields=[
                ('modulo_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='web.Modulo')),
                ('grados', models.IntegerField(default=None, null=True)),
                ('humedad', models.IntegerField(default=None, null=True)),
            ],
            bases=('web.modulo',),
        ),
    ]
