# Generated by Django 2.2.1 on 2019-07-10 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modulo',
            name='topic',
            field=models.CharField(default=None, max_length=50, unique=True),
        ),
    ]
