# Generated by Django 2.2.1 on 2019-08-02 16:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dht',
            name='fechaTMax',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='dht',
            name='fechaTMin',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='dht',
            name='humedadMax',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='dht',
            name='humedadMin',
            field=models.FloatField(default=None, null=True),
        ),
    ]
