# Generated by Django 2.2.1 on 2019-05-09 17:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='rfid',
            fields=[
                ('modulo_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='web.Modulo')),
                ('uid', models.CharField(default=None, max_length=50)),
            ],
            bases=('web.modulo',),
        ),
    ]
