# Generated by Django 2.2.1 on 2019-07-12 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_auto_20190710_1609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dht',
            name='humedad',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='dht',
            name='temperatura',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='ldr',
            name='luminosidad',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='mq2',
            name='co2',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='mq2',
            name='lpg',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='mq2',
            name='smoke',
            field=models.FloatField(default=None, null=True),
        ),
    ]
