# Generated by Django 2.2.4 on 2019-08-13 15:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_led_auto'),
    ]

    operations = [
        migrations.AddField(
            model_name='led',
            name='horaFin',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='led',
            name='horaInicio',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
    ]
