# Generated by Django 2.2.1 on 2019-08-02 16:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_auto_20190802_1817'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dht',
            name='fechaTMin',
        ),
        migrations.AddField(
            model_name='dht',
            name='fechaHMin',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
