# Generated by Django 2.2.1 on 2019-05-09 20:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_rfid'),
    ]

    operations = [
        migrations.CreateModel(
            name='ldr',
            fields=[
                ('modulo_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='web.Modulo')),
                ('voltaje', models.IntegerField(default=None, null=True)),
            ],
            bases=('web.modulo',),
        ),
        migrations.CreateModel(
            name='luz',
            fields=[
                ('modulo_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='web.Modulo')),
                ('luminosidad', models.IntegerField(default=0, null=True)),
            ],
            bases=('web.modulo',),
        ),
        migrations.CreateModel(
            name='mq2',
            fields=[
                ('modulo_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='web.Modulo')),
                ('lpg', models.IntegerField(default=None, null=True)),
                ('co2', models.IntegerField(default=None, null=True)),
                ('smoke', models.IntegerField(default=None, null=True)),
            ],
            bases=('web.modulo',),
        ),
        migrations.CreateModel(
            name='puerta',
            fields=[
                ('modulo_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='web.Modulo')),
                ('estado', models.BooleanField(default=False)),
            ],
            bases=('web.modulo',),
        ),
        migrations.RenameField(
            model_name='dht',
            old_name='grados',
            new_name='temperatura',
        ),
    ]
