# Generated by Django 2.2.1 on 2019-07-26 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_auto_20190726_1437'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modulo',
            name='descripcion',
            field=models.CharField(default=None, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='modulo',
            name='nombre',
            field=models.CharField(default=None, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='modulo',
            name='tipo',
            field=models.CharField(choices=[('rfid', 'rfid'), ('dht', 'dht'), ('mq2', 'mq2'), ('ldr', 'ldr'), ('led', 'led'), ('puerta', 'puerta')], default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='modulo',
            name='topic',
            field=models.CharField(default=None, max_length=50, null=True, unique=True),
        ),
    ]
