# Generated by Django 2.2.4 on 2019-08-13 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_auto_20190813_1701'),
    ]

    operations = [
        migrations.AddField(
            model_name='led',
            name='nivelProgramado',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
