# Generated by Django 2.2.1 on 2019-08-02 16:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_auto_20190802_1821'),
    ]

    operations = [
        migrations.AddField(
            model_name='dht',
            name='fechaHMax',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='dht',
            name='fechaTMin',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
