# Generated by Django 2.2.1 on 2019-07-13 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_auto_20190712_1353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='uid',
            field=models.CharField(default=None, max_length=250, unique=True),
        ),
    ]
