# Generated by Django 2.2.1 on 2019-05-10 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_auto_20190509_2220'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='luz',
            new_name='led',
        ),
    ]
