# Generated by Django 2.2.1 on 2019-08-02 16:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_auto_20190802_1822'),
    ]

    operations = [
        migrations.AddField(
            model_name='dht',
            name='horaHMax',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='dht',
            name='horaTMax',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
    ]
