# Generated by Django 2.2.1 on 2019-05-11 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_auto_20190510_1833'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modulo',
            name='fecha',
        ),
        migrations.AddField(
            model_name='modulo',
            name='tipo',
            field=models.CharField(choices=[('RFID', 'RFID'), ('Temperatura-Humedad', 'Temperatura-Humedad'), ('Gas', 'Gas'), ('Luminosidad', 'Luminosidad'), ('Luz', 'Luz'), ('Puerta', 'Puerta')], default=None, max_length=50),
        ),
    ]
