# Generated by Django 2.2.1 on 2019-08-02 16:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_auto_20190802_1843'),
    ]

    operations = [
        migrations.AddField(
            model_name='dht',
            name='horaHMin',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='dht',
            name='horaTMin',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
    ]
