# Generated by Django 2.2.1 on 2019-07-26 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_auto_20190726_1618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modulo',
            name='codigoHogar',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
    ]
