# Generated by Django 2.2.4 on 2019-08-14 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_auto_20190813_1743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='led',
            name='nivelProgramado',
            field=models.CharField(choices=[(124, 'Baja'), (512, 'Media'), (1024, 'Máxima')], default=None, max_length=50),
        ),
    ]
