# Generated by Django 2.2.4 on 2019-08-14 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_auto_20190814_1343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='led',
            name='nivelProgramado',
            field=models.CharField(choices=[('Baja', 'Baja'), ('Media', 'Media'), ('Máxima', 'Máxima')], default=None, max_length=50),
        ),
    ]
