# Generated by Django 2.2.4 on 2019-08-14 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_auto_20190814_1344'),
    ]

    operations = [
        migrations.AddField(
            model_name='led',
            name='flagAuto',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='led',
            name='flagEnvio',
            field=models.BooleanField(default=False),
        ),
    ]
