# Generated by Django 2.2.1 on 2019-05-25 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0010_auto_20190525_1202'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfil',
            name='dht',
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='ldr',
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='led',
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='mq2',
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='puerta',
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='rfid',
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='uid',
        ),
        migrations.AddField(
            model_name='perfil',
            name='bio',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='perfil',
            name='web',
            field=models.URLField(blank=True),
        ),
    ]
