# Generated by Django 2.2.4 on 2019-08-15 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0010_registrodht'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dht',
            name='fechaHMax',
        ),
        migrations.RemoveField(
            model_name='dht',
            name='fechaHMin',
        ),
        migrations.RemoveField(
            model_name='dht',
            name='fechaTMax',
        ),
        migrations.RemoveField(
            model_name='dht',
            name='fechaTMin',
        ),
        migrations.RemoveField(
            model_name='registrodht',
            name='fechaHMax',
        ),
        migrations.RemoveField(
            model_name='registrodht',
            name='fechaHMin',
        ),
        migrations.RemoveField(
            model_name='registrodht',
            name='fechaTMin',
        ),
    ]
