# Generated by Django 2.2.4 on 2019-08-15 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0011_auto_20190815_1946'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registrodht',
            old_name='fechaTMax',
            new_name='fecha',
        ),
    ]
