# Generated by Django 2.2.1 on 2019-05-25 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0012_auto_20190525_1725'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='dht',
            field=models.ManyToManyField(blank=True, to='web.dht'),
        ),
    ]
