# Generated by Django 2.2.1 on 2019-05-25 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0013_perfil_dht'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='rfid',
            field=models.ManyToManyField(blank=True, to='web.rfid'),
        ),
    ]
