# Generated by Django 2.2.4 on 2019-08-16 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0014_dht_incidencia'),
    ]

    operations = [
        migrations.RenameField(
            model_name='incidenciadht',
            old_name='horaHMax',
            new_name='hora',
        ),
        migrations.RenameField(
            model_name='incidenciadht',
            old_name='humedadMax',
            new_name='humedad',
        ),
        migrations.RenameField(
            model_name='incidenciadht',
            old_name='temperaturaMax',
            new_name='temperatura',
        ),
        migrations.RemoveField(
            model_name='incidenciadht',
            name='horaHMin',
        ),
        migrations.RemoveField(
            model_name='incidenciadht',
            name='horaTMax',
        ),
        migrations.RemoveField(
            model_name='incidenciadht',
            name='horaTMin',
        ),
        migrations.RemoveField(
            model_name='incidenciadht',
            name='humedadMin',
        ),
        migrations.RemoveField(
            model_name='incidenciadht',
            name='temperaturaMin',
        ),
    ]
