# Generated by Django 2.2.4 on 2019-08-17 12:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0015_auto_20190816_1621'),
    ]

    operations = [
        migrations.AddField(
            model_name='mq2',
            name='co2Max',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='mq2',
            name='horaCO2Max',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='mq2',
            name='horaLPGMax',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='mq2',
            name='horaSMOKEMax',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='mq2',
            name='incidencia',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mq2',
            name='lpgMax',
            field=models.FloatField(default=0, null=True),
        ),
    ]
