# Generated by Django 2.2.1 on 2019-05-25 15:57

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        ('web', '0015_auto_20190525_1732'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('uid', models.CharField(default=None, max_length=250)),
                ('dht', models.ManyToManyField(blank=True, to='web.dht')),
                ('ldr', models.ManyToManyField(blank=True, to='web.ldr')),
                ('led', models.ManyToManyField(blank=True, to='web.led')),
                ('mq2', models.ManyToManyField(blank=True, to='web.mq2')),
                ('puerta', models.ManyToManyField(blank=True, to='web.puerta')),
                ('rfid', models.ManyToManyField(blank=True, to='web.rfid')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.DeleteModel(
            name='Perfil',
        ),
    ]
