# Generated by Django 2.2.1 on 2019-06-11 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0016_auto_20190525_1757'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='dht',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='ldr',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='led',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='mq2',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='puerta',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='rfid',
        ),
    ]
