# Generated by Django 2.2.4 on 2019-08-17 15:16

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0017_mq2_smokemax'),
    ]

    operations = [
        migrations.CreateModel(
            name='registroMQ2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
                ('lpgMax', models.FloatField(default=0, null=True)),
                ('co2Max', models.FloatField(default=0, null=True)),
                ('smokeMax', models.FloatField(default=0, null=True)),
                ('horaLPGMax', models.TimeField(default=django.utils.timezone.now)),
                ('horaCO2Max', models.TimeField(default=django.utils.timezone.now)),
                ('horaSMOKEMax', models.TimeField(default=django.utils.timezone.now)),
                ('mq2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.mq2')),
            ],
        ),
        migrations.CreateModel(
            name='incidenciaMQ2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
                ('lpg', models.FloatField(default=0, null=True)),
                ('co2', models.FloatField(default=0, null=True)),
                ('smoke', models.FloatField(default=0, null=True)),
                ('hora', models.TimeField(default=django.utils.timezone.now)),
                ('mq2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.dht')),
            ],
        ),
    ]
