# Generated by Django 2.2.4 on 2019-08-17 16:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0018_incidenciamq2_registromq2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidenciamq2',
            name='mq2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.mq2'),
        ),
    ]
