# Generated by Django 2.2.4 on 2019-08-18 17:02

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0019_auto_20190817_1806'),
    ]

    operations = [
        migrations.CreateModel(
            name='registroRFID',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
                ('hora', models.TimeField(default=django.utils.timezone.now)),
                ('uid', models.CharField(default=None, max_length=50, null=True)),
                ('rfid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.rfid')),
            ],
        ),
    ]
