# Generated by Django 2.2.4 on 2019-08-20 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0020_registrorfid'),
    ]

    operations = [
        migrations.AddField(
            model_name='rfid',
            name='lastUID',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
    ]
